# Matrix Factorization: Toy Example

This is a quick demo for concepts related to Matrix Factorization for Recommender Systems, inspired by the [Colab Notebook](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/recommendation-systems/recommendation-systems.ipynb) of the ["Recommendation Systems" course](https://developers.google.com/machine-learning/recommendation) created by some kind folks at Google. It uses Google's TensorFlow library.

## Scenario
The goal in Matrix Factorization is to find two matrices, a user matrix $U$ and an item matrix $V$, each having the same number of columns. Multiplied together, those two matrices should approximate some "target matrix" $A$, i.e. those two matrices are *factors* that should (roughly) reproduce $A$ when multiplied together. [This](https://youtu.be/ZspR5PZemcs) video explains the general concept very nicely.

The items and users are described by so-called *embeddings*. Note that the "variables" used for embeddings are the same for both the users and the items! In our case, they are very simple: just three numbers. 

What could those numbers mean? This is very context-dependent. In the case of a movie platform they could be "movie/user profiles", for example three common movie categories. A higher value for a particular variable for a user in $U$ could mean that the user likes this particular type of movie a lot. Similarly, a high value for a particular variable for a movie in $V$ could mean that this movie fits the corresponding genre especially well. 

In our example, both $U$ and $V$ have $d = 3$ columns, while $U$ has $n$ rows and $V$ has $m$ rows. Consequently, $A$ (which should be approximated by $U \cdot V^T$) has shape $n \times m$.

### Import required libraries

In [57]:
# required: TensorFlow 2
import tensorflow as tf

### Initialize matrices

We define very simple example matrices for the rating matrix $A$ and its "factor matrices", $U$ and $V$:

In [58]:
# we need to turn on eager execution to be able to see resulting tensors "live", without needing to call eval() (by calling numpy() on the computed tensors)
# more on eager execution and graphs: https://www.tensorflow.org/guide/intro_to_graphs
tf.config.run_functions_eagerly(False)

U = tf.constant([[3, 4, 5], [2, 5, 3]])
V = tf.constant([[3, 3, 3], [5, 1, 3], [1, 5, 5]])
A = tf.sparse.SparseTensor(
  indices = [[0, 2], [1, 0], [1, 2]],
  values = [44, 32, 38],
  dense_shape = [2, 3])

While executing TensorFlow code eagerly, Tensor's have a `numpy()` function that we can use to inspect their contents:

In [3]:
U.numpy()

array([[3, 4, 5],
       [2, 5, 3]], dtype=int32)

In [4]:
V.numpy()

array([[3, 3, 3],
       [5, 1, 3],
       [1, 5, 5]], dtype=int32)

For printing sparse tensors, we can make use of the following utility function:

In [15]:
def pprint_sparse_tensor(st):
  s = "<SparseTensor\n shape = %s \n values = {" % (st.dense_shape.numpy().tolist(),)
  for (index, value) in zip(st.indices.numpy(), st.values.numpy()):
    s += f"\n  %s: %s," % (index.tolist(), value.tolist())
  print(s + "\n }>")

This is the sparse matrix we would like to approximate with $U \cdot V^T$:

In [16]:
pprint_sparse_tensor(A)

<SparseTensor
 shape = [2, 3] 
 values = {
  [0, 2]: 44,
  [1, 0]: 32,
  [1, 2]: 38,
 }>


## Evaluating quality of Matrix Factorization

In practice, an "ideal" Matrix Factorization is learned by Machine Learning algorithms. As every Machine Learning algorithm needs some loss function to optimize, we will also use one in this example. We will go with the Mean Squared Error (MSE).

### 1. Computing "prediction" (using $U$ and $V$) for existing elements in $A$

This goal is achieved by multiplying $U$ with $V^T$ and keeping only entries that were non-zero in $A$.

#### Simpler (less efficient) approach

Use matrix multiplication and then subset with `tf.gather()`:

In [42]:
matrix_product = U @ tf.transpose(V)
matrix_product.numpy()

array([[36, 34, 48],
       [30, 24, 42]], dtype=int32)

In [44]:
# gather_nd() allows us to pick selected elements from a multi-dimensional tensor via a multi-dimensional tensor of indices
result_a = tf.gather_nd(matrix_product, A.indices)

In [45]:
result_a.numpy()

array([48, 30, 42], dtype=int32)

#### More efficient approach

We only take those pairs of elements from $U$ and $V$ into account that actually appear in the original matrix $A$, so we skip all cases where we would multiply with 0 (or NaN). In practice this makes a lot of sense, as most users have rated only a tiny fraction of all the available items, i.e. the matrix $A$ is very sparse. 

In [32]:
match_indices_U = A.indices[:, 0]
match_indices_V = A.indices[:, 1]

In [33]:
match_indices_U.numpy()

array([0, 1, 1])

In [34]:
match_indices_V.numpy()

array([2, 0, 2])

How does this make sense? Compare with the non-zero indices of $A$:

In [29]:
A.indices.numpy()

array([[0, 2],
       [1, 0],
       [1, 2]])

In [31]:
#  TODO: finish
#  def sparse_2d_tensor_to_dense_2d_array(sparse):
#   matrix = np.ndarray(shape = sparse.dense_shape.numpy())
#   for i, pos in enumerate(sparse.indices.numpy().tolist()):
#     matrix[pos]

So, the elements we would consider are:

In [36]:
# gather() allows us to pick selected elements from a tensor via a tensor of indices
match_partners_U = tf.gather(U, match_indices_U)
match_partners_V = tf.gather(V, match_indices_V)

Now, we do element-wise multiplication:

In [37]:
elementwise = match_partners_U * match_partners_V

In [38]:
elementwise.numpy()

array([[ 3, 20, 25],
       [ 6, 15,  9],
       [ 2, 25, 15]], dtype=int32)

And, finally, sum by row:

In [39]:
result_b = tf.reduce_sum(elementwise, axis = 1)

In [40]:
result_b.numpy()

array([48, 30, 42], dtype=int32)

The result is identical to the other approach, nice!

### 2. Computing MSE from prediction

Our prediction was:

In [46]:
prediction = result_a # result_b is identical
prediction.numpy()

array([48, 30, 42], dtype=int32)

The actual (non-zero) entries in the matrix were:

In [48]:
A.values.numpy()

array([44, 32, 38], dtype=int32)

To compute the MSE, we now just sum up the squared differences for each vector element and divide by the length of the two vectors (or tensors, to be exact). TensorFlow has a utility function for this:

In [54]:
mse = tf.compat.v1.losses.mean_squared_error(A.values, prediction)

In [56]:
mse.numpy()

12.0

That makes sense, we were off by 2 each time, 3 * 2^2 = 12.

## Usage of Matrix Factorization in practice

### How to find "best" Matrix Factorization?

In practice, a ML model (most probably a neural network) would "learn" a good matrix factorization over several iterations, each time trying to minimize the loss function. In neural networks, "Stochastic Gradient Descent" is commonly used for that purpose.

### How to use for recommendations?

The whole purpose of Matrix factorization is to use it for predictions on new, unseen data. The matrix factorization $U \cdot V^T$ can be thought of as a "score matrix" for item/user combinations. By learning a good approximation for $A$, we implicitly also learn "expected scores" for combinations of users and items that didn't occur up until now. This means, that for recommending a new item to a user, we can simply have a look at that user's row in $U \cdot V^T$ and pick the element with the highest score! The index of that element is the item we should try to recommend first!